#!/usr/bin/env node
/** Generate or verify embedded CSS from the vendored website token release. */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';

const packageDir = dirname(fileURLToPath(import.meta.url));
const root = dirname(packageDir);
const args = process.argv.slice(2);
const check = args.includes('--check');
const source = readFileSync(join(packageDir, 'tokens.json'), 'utf8');
const tokens = JSON.parse(source);
const { consumer } = JSON.parse(readFileSync(join(packageDir, 'consumer.json'), 'utf8'));
if (!/^\d+\.\d+\.\d+$/.test(tokens.version)) throw new Error('Token version must be semver.');
const digest = createHash('sha256').update(source).digest('hex');
const files = ['tokens.json', 'generate.mjs', 'README.md'];
const targets = {
  site: [['ai/src/styles/cobalt.css', 'site-dark'], ['ai/src/styles/modern-light.css', 'site-light']],
  hub: [['web/src/routes/layout.css', 'hub']],
  edge: [['console/styles.css', 'edge'], ['docs/guide/guide.css', 'guide']],
};
if (!(consumer in targets)) throw new Error(`Unknown consumer ${consumer}`);
const declaration = (values, indent = '\t') => Object.entries(values).map(([key, value]) => `${indent}--${key}: ${value};`).join('\n');
const shared = (profile) => ({ ...tokens.foundations, ...tokens.aliases, ...tokens.profiles[profile] });
const block = (selector, theme, profile, foundations = false) => `${selector} {\n\tcolor-scheme: ${theme};\n${declaration({ ...(foundations ? shared(profile) : {}), ...tokens.themes[theme] })}\n}`;
function render(id) {
  const header = `/* Website design tokens ${tokens.version}; source SHA-256 ${digest}.\n * Generated by design-tokens/generate.mjs. Edit the website source, then sync. */`;
  let body;
  if (id === 'site-dark') body = block(':root', 'dark', 'site', true);
  else if (id === 'site-light') body = block("html:root[data-design='light']", 'light', 'site');
  else if (id === 'hub') {
    body = `:root {\n${declaration(shared('hub'))}\n}\n\n${block(":root,\n[data-theme='light']", 'light', 'hub')}\n\n${block("[data-theme='dark']", 'dark', 'hub')}\n\n@media (prefers-color-scheme: dark) {\n${block(":root[data-theme='system']", 'dark', 'hub').split('\n').map((line) => `\t${line}`).join('\n')}\n}`;
  } else body = `${block(':root', 'light', id, true)}\n\n${block(':root[data-theme="dark"]', 'dark', id)}`;
  return `/* design-tokens:start ${id} */\n${header}\n${body}\n/* design-tokens:end ${id} */`;
}
let failed = false;
for (const [relative, id] of targets[consumer]) {
  const path = join(root, relative);
  const current = readFileSync(path, 'utf8');
  const start = `/* design-tokens:start ${id} */`;
  const end = `/* design-tokens:end ${id} */`;
  const from = current.indexOf(start), to = current.indexOf(end);
  if (from < 0 || to < from || current.indexOf(start, from + 1) !== -1) throw new Error(`Missing or duplicate token slot: ${relative}`);
  const expected = current.slice(0, from) + render(id) + current.slice(to + end.length);
  // Core colour/geometry/type declarations belong to the release, not hidden local overrides.
  const outside = current.slice(0, from) + current.slice(to + end.length);
  const protectedNames = new Set([...Object.keys(tokens.themes.light), ...Object.keys(tokens.foundations)]);
  for (const match of outside.matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) {
    if (protectedNames.has(match[1])) throw new Error(`Unowned token override --${match[1]} in ${relative}`);
  }
  if (current !== expected) {
    if (check) { console.error(`Token drift: ${relative}. Run node design-tokens/generate.mjs.`); failed = true; }
    else writeFileSync(path, expected);
  }
}
for (const flag of ['--compare', '--sync']) {
  const index = args.indexOf(flag);
  if (index === -1) continue;
  if (consumer !== 'site') throw new Error(`${flag} is only supported from the authoritative website checkout.`);
  const destinations = args.slice(index + 1).filter((arg) => !arg.startsWith('--'));
  if (!destinations.length) throw new Error(`${flag} requires repository paths.`);
  for (const destination of destinations) {
    const targetRoot = resolve(destination);
    const targetPackage = join(targetRoot, 'design-tokens');
    if (flag === '--sync') {
      mkdirSync(targetPackage, { recursive: true });
      for (const file of files) copyFileSync(join(packageDir, file), join(targetPackage, file));
      const result = spawnSync(process.execPath, [join(targetPackage, 'generate.mjs')], { stdio: 'inherit' });
      if (result.status !== 0) failed = true;
    } else {
      for (const file of files) {
        if (!readFileSync(join(packageDir, file)).equals(readFileSync(join(targetPackage, file)))) {
          console.error(`Release drift: ${targetRoot}/design-tokens/${file}`); failed = true;
        }
      }
      const result = spawnSync(process.execPath, [join(targetPackage, 'generate.mjs'), '--check'], { stdio: 'inherit' });
      if (result.status !== 0) failed = true;
    }
  }
}
if (failed) process.exitCode = 1;
else console.log(`${consumer}: design tokens ${tokens.version} ${check ? 'verified' : 'generated'}`);
